[[redirects]]
  from = "https://prompt.sutmeme.com/*"
  to = "https://promptlabai.com/th/:splat"
  status = 301
  force = true
[[redirects]]
  from = "https://promptlab.sutmeme.com/*"
  to = "https://promptlabai.com/th/:splat"
  status = 301
  force = true
[[redirects]]
  from = "https://promptlabai.com/"
  to = "https://promptlabai.com/th/"
  status = 301
  force = true
